FROM node:25-alpine

WORKDIR /app


RUN npm install -g pnpm
RUN pnpm approve-builds esbuild @tsparticles/engine

COPY package*.json pnpm-lock.yaml pnpm-workspace.yaml ./
RUN pnpm install

COPY . .

EXPOSE 5173

CMD ["pnpm", "run", "dev"]