
services:
  backend:
    image: kawambiit/esr-backend:dev-latest
    build:
      dockerfile: ./server/Dockerfile
    ports:
      - "8000:3000"
  frontend:
    image: kawambiit/esr-frontend:dev-latest
    build:
      dockerfile: ./client/Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - backend
