
services:
  easternskyradio:
    image: kawambiit/easternskyradio:latest
    ports:
      - "8000:3000"
    volumes:
      - /home/ubuntu/codingprojects/esr/dist:/usr/src/app/client/dist
    env_file:
      - stack.env
  caddy:
    image: kawambiit/esr-caddy:latest
    ports:
      - "8080:80"
    depends_on:
      - easternskyradio
