name: CI/CD Pipeline

on:
  push:
    branches:
      - '**'



jobs:
  lint-backend:
    runs-on: ubuntu-latest


    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: "Set up bun"
        uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: bun install

      - name: Run linter
        run: bun run lint
        working-directory: ./server
  lint-frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./client

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: "Set up node"
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      

      - name: "Install pnpm"
        run: "npm install -g pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Run linter
        run: pnpm run lint


  backend-tests:
    runs-on: ubuntu-latest
    env:
      NODE_ENV: "gh_test"
      MONGODB_URI: "mongodb://mongodb:27017/easternSkyRadio_test"
      EXP_SESSION_SECRET: "test_secret"
      TEST_MIGRATIONS: false
    services:
      mongodb:
        image: mongo:latest
        ports:
          - 27017:27017
    defaults:
      run:
        working-directory: ./server


    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: "Set up bun"
        uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: bun install

      - name: Run tests
        run: bun run test


